{% set name = "llama-index-agent-openai" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/llama_index_agent_openai-{{ version }}.tar.gz
    sha256: ffd6228e02714e0ea3bd71ca47dc948b3ccc04525937e91218267d19a22aec16
  # https://github.com/run-llama/llama_index/issues/10806
  - url: https://raw.githubusercontent.com/run-llama/llama_index/main/LICENSE
    sha256: 24f40b5190fdacabc24ddbb5f76364d15e4f030925220ea300d8a2dd4993c8cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - llama-index-utils-openai >=0.1.0,<0.2.0
    - openai >=1.14.0
    - python >=3.8.1,<4.0
    - llama-index-core >=0.11.0,<0.12.0
    - llama-index-llms-openai >=0.2.0,<0.3.0

test:
  imports:
    - llama_index.agent.openai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://llamaindex.ai
  dev_url: https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/agent/llama-index-agent-openai
  summary: llama-index agent openai integration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
